name: 更新每日论文workFlow

on:
  schedule:
    - cron: '0 16 * * *'  # UTC 16:00 (+8即为北京时间 00:00)
  workflow_dispatch:    # 允许手动触发
  push:                # 在推送时触发
    branches:
      - main        # 只在推送到 main 分支时触发

permissions:
  contents: write
  issues: write

jobs:
  update_daily_papers:
    runs-on: windows-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 设置 Rust 环境
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: 恢复 Just 缓存
      id: restore-just
      uses: actions/cache/restore@v3
      with:
        path: |
          C:\Users\runneradmin\.cargo\bin\just.exe
        key: ${{ runner.os }}-just-${{ hashFiles('**/Cargo.lock') }}

    - name: 安装 Just 工具
      if: steps.restore-just.outputs.cache-hit != 'true'
      run: |
        cargo install --debug just
        echo "C:\Users\runneradmin\.cargo\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: 保存 Just 缓存
      if: steps.restore-just.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        path: |
          C:\Users\runneradmin\.cargo\bin\just.exe
        key: ${{ runner.os }}-just-${{ hashFiles('**/Cargo.lock') }}

    - name: 运行每日更新
      run: just

    - name: 提交更改
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: '✏️ 自动更新论文'
        file_pattern: 'README.md .github/ISSUE_TEMPLATE.md'
        commit_user_name: ${{ github.actor }}
        commit_user_email: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
        push_options: '--force'

    - name: 创建 Issue 通知
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        update_existing: true
